tabspaces = 4

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 13.0

[selection]
save_to_clipboard = false

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/fish"

[window]
decorations = "full"
opacity = 0.99

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 8
y = 0
